---
- name: Docker Configuration and Creation
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
      - name: Starting Todo App from Docker-Compose
        remote_user: wush
        community.docker.docker_compose:
            project_src: /home/thedudebridge
      - name: Setting Docker Service to start on reboot
        command: sudo systemctl enable docker.service
        become: yes
      - name: Setting Containerd Service to start on reboot
        command: sudo systemctl enable containerd.service
        become: yes