---
- name: Docker Configuration and Creation
  hosts: all
  become: yes
  tasks:
      - name: Install docker packages
        remote_user: wush
        apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
        with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        tags:
          - docker
      - name: Add Docker s official GPG key
        remote_user: wush
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
        tags:
          - docker
      - name: Verify that we have the key with the fingerprint
        remote_user: wush
        apt_key:
          id: 0EBFCD88
          state: present
        tags:
          - docker
      - name: Set up the stable repository
        remote_user: wush
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
          state: present
          update_cache: yes
        tags:
          - docker
      - name: Update apt packages
        remote_user: wush
        apt:
          update_cache: yes
        tags:
          - docker
      - name: Install docker
        remote_user: wush
        apt:
          name: docker-ce
          state: present
          update_cache: yes
        #notify: Start docker on boot
        tags:
          - docker
      - name: Add remote "ubuntu" user to "docker" group
        remote_user: wush
        user:
          name: "wush"
          group: "docker"
          append: yes
        tags:
          - docker
      - name: Install docker-compose
        remote_user: wush
        get_url: 
          url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
          dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'
      - name: Pulling Todo App from Github
        remote_user: wush
        git:
            repo: https://github.com/wussh/thedudebridge.git
            dest: /home/wush/
            version: main
      - name: Starting Todo App from Docker-Compose
        remote_user: wush
        community.docker.docker_compose:
            project_src: /home/wush/thedudebridge/
            files:
            - docker-compose.yml
      - name: Setting Docker Service to start on reboot
        command: sudo systemctl enable docker.service
        become: yes
      - name: Setting Containerd Service to start on reboot
        command: sudo systemctl enable containerd.service
        become: yes